version: '3'
services:
  marketplace-projector:
    image: 350661628111.dkr.ecr.us-east-1.amazonaws.com/marketplace-crawler
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
